--create SCHEMA GERENCIADOR;

DROP TABLE GERENCIADOR.PROFISSIONAL;
DROP TABLE GERENCIADOR.FUNCAO;

CREATE TABLE GERENCIADOR.PROFISSIONAL(
PROF_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (start with 0,increment by 1),
FUNC_ID INTEGER ,
USUA_ID INTEGER ,
PROF_NOME VARCHAR(25),
PROF_CPF VARCHAR(15),
PROF_GRAU_INSTRUCAO VARCHAR(3),
PROF_DT_NASCIMENTO DATE,
PROF_DT_ADMISSAO DATE,
PRIMARY KEY (FUNC_ID)
);

CREATE TABLE GERENCIADOR.FUNCAO(
FUNC_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (start with 0,increment by 1),
FUNC_DESCRICAO VARCHAR(25),
PRIMARY KEY (FUNC_ID)
);